[package]
name = "tip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12"
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "3.1.0", features = ["derive"] }
